# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 08:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rant', '0002_auto_20171213_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rant_title', models.CharField(max_length=255)),
                ('rant_content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rant.Profile')),
            ],
        ),
    ]
