# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rant', '0003_rant'),
    ]

    operations = [
        migrations.AddField(
            model_name='rant',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
