# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rant', '0005_auto_20171214_1447'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reaction',
            options={},
        ),
    ]
